name: Tests

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes libvips
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install project and dependencies
        run: uv pip install --system ".[tests]"
      - name: Test with pytest
        run: uv run pytest
